# Generated by Django 2.2.1 on 2019-05-20 13:28

from django.db import migrations, models
import webcrawltoapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantsPest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.CharField(max_length=120)),
                ('Origin', models.CharField(max_length=120)),
                ('Secure_any_suspect_specimens', models.TextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to=webcrawltoapp.models.upload_image_path)),
            ],
        ),
    ]
